### PR TITLE
Folium tutorial

### PR DESCRIPTION
**Pull request by acannistra**
Here's a first draft of the Folium tutorial. It covers: 

* How to begin and save a simple Folium map in Python
* Basics of markers and polygons
* How to interface with shapefiles and other geospatial data using Geopandas and GeoJson
* Different basemaps
* Practicing synthesizing these skills with real data and producing customizable HTML popups. 

I think this is a fairly good amount, but it *does not* cover arguably the most poweful but challenging-to-learn part of folium: its choropleth feature. I think I'm going to work on adding a small tutorial on this to the bottom of this document, so I'm not sure we should merge yet. 

If @rjleveque and others want to give it a look, the rendered version is accessible [here](https://nbviewer.jupyter.org/github/acannistra/visualization/blob/51fddd62f61eaf1846cde6b3e212e51aeaa62975/docker/notebooks/foliumTutorial.ipynb) (but the links which reference locally-rendered files won't work).

### CODE REVIEW

**Comment by acannistra** [comment]
I'm not sure why all of the commits from my other PR came through with this one. It could be because I started the 'foliumTutorial.ipynb' file a while ago.

**Comment by rjleveque** [comment]
@acannistra Probably all the commits are here because your other PR hasn't been merged yet.  

I'm planning to look at these this afternoon, and will try to merge them in.
Thanks!

**Comment by acannistra** [comment]
Thanks. Let me know if you think adding more to this tutorial would be worthwhile. If not, we can merge, but if so I'd like to add that additional material before merging.

**Comment by rjleveque** [comment]
Looks good, and sadly no shortage of river flooding data to visualize now.

It would be great to add a cloropleth example.  Is there an easy way to take general spatial data (e.g. some of the tsunami inundation depth data used in the `Crescent_City_Inundation.ipynb` notebook) and plot on a map?  Does the data need to be mapped to GeoJSON form first and then do a cloropleth?

It might be worth pointing to [colorbrewer](http://colorbrewer2.org/#) for advice on choosing color maps.

Another thing I would like to be able to do is click on an interactive map and have a callback return the coordinates of the point, or better yet coordinates of a rectangle or polygon selected with the mouse.  I've done this with ipyleaflet in the past, but it would be nice to combine this with plotting data on the map.

**Comment by acannistra** [comment]
9022e54 adds a choropleth tutorial, and can be viewed [here](https://nbviewer.jupyter.org/github/acannistra/visualization/blob/9022e541b1f8629ea789a32d877039648ce0e886/docker/notebooks/foliumTutorial.ipynb). The choropleth is too large to be rendered in the notebook, but looks something like this: screenshot

I'm gonna go ahead and merge this one.

**Comment by rjleveque** [comment]
@acannistra:  You've got a line

```
    iframe = folium.IFrame(html=completePopup, width=530, height=425)
```
that overwrites the definition of `iframe` from the first cell and then this function no longer works in the last executable cell.

**Comment by acannistra** [comment]
Great, I'll make that change. ASAP.

**Pull request merged**
