### PR TITLE
2018 Reboot: Schedule Restructure, Carpentries Format

### PR DESCRIPTION
**Pull request by acannistra**
Starting PR for this year's visualization tutorial. **Not ready for merging yet**. 

Wanted to get this up just so other folks on organizing committee can see the broad view of what's going to be taught. 

### Remaining Tasks:

- [ ] Determine timing for episodes
- [ ] Finish episodes (geopandas/cartopy; interactive/folium; other tools)
- [ ] Decide on tools for "Other Tools" episode (Tableau, GeoViews/Datashader?)

### CODE REVIEW

**Comment by acannistra** [comment]
@catherinekuhn @emiliom expressed interest in seeing materials covered. Currently I'm teaching:

* General projections
* Cartopy for simple plots
* Cartopy with Geopandas
* Interactive plotting (likely going to use a folium hands-on example)
* Broad-brush examples with other tools, without much tutorial (going to show a [tableau dashboard](https://public.tableau.com/profile/tony.cannistra#!/vizhome/wildernesses-over-time/TheHistoryofWilderness) that I created using geospatial data, and probably talk briefly about Holoviews/Geoviews/datashader example for massive datasets and the [mapbox competitor](https://github.com/mapbox/mapboxgl-jupyter) to folium.

**Comment by emiliom** [comment]
Thanks @acannistra !

**Comment by catherinekuhn** [comment]
Awesome! I can't wait to see it! Nice work @acannistra.

**Comment by acannistra** [comment]
Ready to go.

**Pull request merged**
